// src/ecs/constants/weapons.js

export const WEAPONS = [
    {
        id: 0,
        name: "raygun",
        category: "bullet",
        damage: 10,
        maxBullets: 128,
        hitRadius: 0.5,
        fireRate: 0.15,
        speed: 18,
        lifetime: 1.2,
        projectileCount: 1,
        spreadAngle: 0,
        color: "#e8fff5",
        glowColor: "#66ffcc",
        haloColor: "#77ffdd",
    },
    {
        id: 1,
        name: "shotgun",
        category: "bullet",
        damage: 12,
        maxBullets: 128,
        hitRadius: 0.6,
        fireRate: 0.35,
        speed: 16,
        lifetime: 1.0,
        projectileCount: 3,
        spreadAngle: 0.20,
        color: "#fff2b0",
        glowColor: '#ffe605',
        haloColor: "#ff8800",
    },
    {
        id: 2,
        name: "machinegun",
        category: "bullet",
        damage: 5,
        maxBullets: 128,
        hitRadius: 0.5,
        fireRate: 0.07,
        speed: 22,
        lifetime: 0.9,
        projectileCount: 1,
        spreadAngle: 0.05,
        color: "#c9e8ff",
        glowColor: "#5599ff",
        haloColor: "#3366ff",
    },

    {
        id: 3,
        name: "missilegun",
        trail: true,
        trailColor: "#3366ff",

        damage: 30,
        category: "bullet",
        maxBullets: 128,
        hitRadius: 1.0,
        fireRate: 0.8,
        speed: 10,
        lifetime: 3.0,
        projectileCount: 1,
        spreadAngle: 0,
        color: "#ffaa00",
        glowColor: "#ff6600",
        haloColor: "#ff2200",
        turnRate: 3.0,

    },
    {
        id: 4,
        name: "lasergun",
        category: "beam",
        //    maxBullets: 128,
        hitRadius: 0.3,
        range: 30,
        damagePerSecond: 40,
        beamWidth: 0.11,
        tickSparkInterval: 0.05,
        color: "#ffe0ee",
        glowColor: "#ff0055",
        haloColor: "#ff0033",
    },

    {
        id: 5,
        name: "grenadegun",
        category: "bullet",
        trail: true,
        trailColor: "#7DF9FF",

        explosive: true,
        explosionRadius: 2.5,
        damage: 25,
        maxBullets: 32,
        hitRadius: 0.6,
        fireRate: 0.9,
        speed: 12,
        lifetime: 1.6,
        projectileCount: 1,
        spreadAngle: 0,
        color: "#ffcf80",
        glowColor: "#ff9933",
        haloColor: "#ff7700",
    },

    {
        id: 6,
        name: "acidsprayer",
        category: "thrower",
        leavesHazard: true,
        damage: 3,
        hazardRadius: 1.5,
        hazardDamage: 4,
        hazardTickInterval: 0.3,
        hazardDuration: 3.0,
        maxBullets: 96,
        hitRadius: 0.4,
        fireRate: 0.12,
        speed: 15,
        lifetime: 0.8,
        projectileCount: 1,
        spreadAngle: 0.08,
        color: "#ccff66",
        glowColor: "#99ff00",
        haloColor: "#669900",
    },

    {
        id: 7,
        name: "cryocannon",
        category: "bullet",
        freezeDuration: 2.5,
        damage: 4,
        maxBullets: 64,
        hitRadius: 0.5,
        fireRate: 0.3,
        speed: 17,
        lifetime: 1.2,
        projectileCount: 1,
        spreadAngle: 0,
        color: "#c9f5ff",
        glowColor: "#66e0ff",
        haloColor: "#0099cc",
    },

    {
        id: 8,
        name: "arcgun",
        category: "beam",
        jagged: true,
        range: 14,
        damagePerSecond: 35,
        chainDamagePerSecond: 14,
        chainCount: 3,
        chainRange: 5,
        beamWidth: 0.09,
        tickSparkInterval: 0.06,
        color: "#fffbe8",
        glowColor: "#1F51FF",
        haloColor: "#0818A8",
    },

    {
        id: 9,
        name: "flamethrower",
        category: "thrower",
        range: 6,
        coneAngle: 0.6,
        damagePerSecond: 35,
        tickSparkInterval: 0.06,
        color: "#ffcc66",
        glowColor: "#ff6600",
        haloColor: "#ff2200",
    },

    {
        id: 10,
        name: "prismbeam",
        category: "beam",
        range: 20,
        damagePerSecond: 18,
        beamCount: 3,
        beamSpread: 0.35,
        tickSparkInterval: 0.08,
        beamWidth: 0.08,
        color: "#ffe0ff",
        glowColor: "#ff66ff",
        haloColor: "#cc00cc",
    },

    {
        id: 11,
        name: "proximityminelayer",
        category: "mine",
        hazardRadius: 2.0,
        hazardDamage: 40,
        hazardTickInterval: 999,
        hazardDuration: 8.0,
        fireRate: 1.0,
        color: "#ff6666",
        glowColor: "#ff2222",
        haloColor: "#aa0000",
    },

    {
        id: 12,
        name: "particlebeam",
        category: "beam",
        range: 25,
        damagePerSecond: 15,
        maxDamagePerSecond: 60,
        rampTime: 2.0,
        beamWidth: 0.15,
        color: "#ffffff",
        glowColor: "#88ddff",
        haloColor: "#3399ff",
    },

    {
        id: 13,
        name: "darkmattergun",
        category: "launcher",
        leavesHazard: true,
        damage: 0,
        hazardRadius: 3.0,
        hazardDamage: 6,
        hazardTickInterval: 0.5,
        hazardDuration: 4.0,
        maxBullets: 32,
        hitRadius: 0.5,
        fireRate: 1.0,
        speed: 14,
        lifetime: 2.0,
        projectileCount: 1,
        spreadAngle: 0,
        color: "#c9a3ff",
        glowColor: "#7a33ff",
        haloColor: "#4d0099",
    },

]

export function getWeapon(id) {
    return WEAPONS[id] ?? WEAPONS[0]
}